baseurl = "https://shutej.github.io"
languageCode = "en-us"
title = "Jeremy Shute"
[params]
    Description = "My thoughts, exactly."
    github = "shutej"
    linkedin = "shutej"
    twitter = "shutej"
    facebook = "shutej"
